### PR TITLE
Paintera convert

### LINKED ISSUE #13: Store absolute root path for n5-filesystem label-to-block-mapping
If given a relative output path, `paintera-conversion-helper` will store this relative path as `root` in the `labelBlockLookup` entry when creating a project with `label-block-mapping` using n5.
This way, paintera will only find the label-bock mapping, and consequently only generate meshes, if it is called from the same folder.
Instead, the path should be turned into an absolute path, s.t. paintera can be called from any directory.

### LINKED ISSUE #26: Update CLI with more flexible argument groups in picocli 4.0.0
This should be like in https://github.com/saalfeldlab/paintera/pull/273 to get rid of the clunky `container,dataset,type[,target_dataset]` syntax.

### PR DESCRIPTION
**Pull request by hanslovsky**
This pull requests refactors the `CommandLineConverter` into the `PainteraConvert` class to make use of argument groups introduced in picocli 4.0.0. This allows for a better syntax for adding datasets without the cumbersome and error-prone comma-based syntax.

It also checks for existence of input containers and datasets and output datasets (if not explicitly overwritten) and produces more meaningful error messages as requested by @constantinpape

Fixes #26
Fixes #13

### CODE REVIEW

**Comment by hanslovsky** [comment]
@constantinpape can you try this PR?
```sh
git clone https://github.com/saalfeldlab/paintera-conversion-helper
cd paintera-conversion-helper
git checkout paintera-convert
mvn clean install
# sanity check
jgo \
  -Dspark.master='local[*]' \
  org.janelia.saalfeldlab:paintera-conversion-helper:0.8.2-SNAPSHOT:@PainteraConvert \
  --help
# more involved example using cremi sample A from https://cremi.org/static/data/sample_A_20160501.hdf
jgo \
  -Dspark.master='local[*]' \
  org.janelia.saalfeldlab:paintera-conversion-helper:0.8.2-SNAPSHOT:@PainteraConvert \
  --scale 2,2,1 2,2,1 2,2,1 2 2 \
  --revert-array-attributes \
  --output-container=paintera-converted.n5 \
  --container=sample_A_20160501.hdf \
    -d volumes/raw \
      --target-dataset=volumes/raw2 \
      --dataset-scale 3,3,1 3,3,1 2 2 \
      --dataset-resolution 4,4,40.0 \
    -d volumes/labels/neuron_ids
```

A few things to note:
 1. raw datasets cannot be overwritten currently (but a PR is already on the way for it: https://github.com/saalfeldlab/n5-spark/pull/12) and it fails not very gracefully. I would wait until said PR is merged and released before I merge this.
 2. Sometimes I randomly get null pointer exceptions when trying to deserialize the n5 version from the container. Let me know if that happens to you, too.
 3. I added redundant option to set things like resolution or downscaling factors (a) globaly, (b) at container level, and (c) at dataset level. I think this may be useful but is it too confusing? Would you rather just have one layer of options and run the command multiple times instead?
 4. (Redundant) options need more doc but I will wait until I hear your opinion on (3)
 5. Does the long help message make sense to you? Does it give a better (if superficial) understanding of the conversion? 
 6. Is the note for extracting the highest resolution label dataset helpful?

**Comment by constantinpape** [comment]
@hanslovsky looks very promising. I don't have time to check it right now, will try to do this in the next few days.

**Comment by hanslovsky** [comment]
I re-wrote the command to use sub-command instead. Now `paintera-convert` has entry points for both conversion into Paintera data and extraction of label data as scalar:
```shell
$ jgo \
  -Dspark.master='local[*]' \
  org.janelia.saalfeldlab:paintera-conversion-helper:0.8.2-SNAPSHOT:@PainteraConvert \
  --help
Usage: paintera-convert [--help] [--version] [COMMAND]
      --help
      --version
Commands:
  to-paintera, tp  Converts arbitrary 3D label and single- or multi-channel raw
                     datasets in N5 or HDF5 containers into a Paintera-friendly
                     format.  A more detailed description is provided after the
                     synopsis/usage.
  to-scalar, ts    Convert non-scalar label data to UINT64 scalar dataset.  The
                     input can be a single-scale dataset, a multi-scale group,
                     or a Paintera dataset.
```
A few things to note:
 - Each subcommand has a separate help message that can be printed with `paintera-convert command --help`
 - The spark master can be set with a `--spark-master` flag now (instead of the `-Dspark.master=local[*]` JVM option)
 - I tested scalar label extraction and the paintera-data-conversion from the help message, i.e
```
paintera-convert to-paintera \
  --scale 2,2,1 2,2,1 2,2,1 2 2 \
  --revert-array-attributes \
  --output-container=paintera-converted.n5 \
  --container=sample_A_20160501.hdf \
    -d volumes/raw \
      --target-dataset=volumes/raw2 \
      --dataset-scale 3,3,1 3,3,1 2 2 \
      --dataset-resolution 4,4,40.0 \
    -d volumes/labels/neuron_ids
```
 - I tried to ensure that all subcommands exit with meaningful exit codes and provide a meaningful error message if necessary. If exceptions happen outside of the code that I control that becomes a little harder, e.g. when no Spark master is defined, but this can be addressed in future PRs:
```
log4j:WARN No appenders could be found for logger (org.janelia.saalfeldlab.label.spark.N5Helpers).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
19/09/16 20:47:25 WARN Utils: Your hostname, mendelssohn resolves to a loopback address: 127.0.1.1; using 192.168.1.219 instead (on interface wlp59s0)
19/09/16 20:47:25 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
19/09/16 20:47:26 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
19/09/16 20:47:26 ERROR SparkContext: Error initializing SparkContext.
org.apache.spark.SparkException: A master URL must be set in your configuration
        at org.apache.spark.SparkContext.<init>(SparkContext.scala:367)
        at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
        at org.janelia.saalfeldlab.paintera.conversion.to.paintera.ToPainteraData$Parameters.call(ToPainteraData.kt:177)
        at org.janelia.saalfeldlab.paintera.conversion.to.paintera.ToPainteraData$Parameters.call(ToPainteraData.kt:112)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1743)
        at picocli.CommandLine.access$900(CommandLine.java:145)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2101)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2068)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1935)
        at picocli.CommandLine.execute(CommandLine.java:1864)
        at org.janelia.saalfeldlab.paintera.conversion.PainteraConvert$Companion.main(PainteraConvert.kt:35)
        at org.janelia.saalfeldlab.paintera.conversion.PainteraConvert.main(PainteraConvert.kt)
19/09/16 20:47:26 ERROR Utils: Uncaught exception in thread main
java.lang.NullPointerException
        at org.apache.spark.SparkContext.org$apache$spark$SparkContext$$postApplicationEnd(SparkContext.scala:2389)
        at org.apache.spark.SparkContext$$anonfun$stop$1.apply$mcV$sp(SparkContext.scala:1904)
        at org.apache.spark.util.Utils$.tryLogNonFatalError(Utils.scala:1360)
        at org.apache.spark.SparkContext.stop(SparkContext.scala:1903)
        at org.apache.spark.SparkContext.<init>(SparkContext.scala:579)
        at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
        at org.janelia.saalfeldlab.paintera.conversion.to.paintera.ToPainteraData$Parameters.call(ToPainteraData.kt:177)
        at org.janelia.saalfeldlab.paintera.conversion.to.paintera.ToPainteraData$Parameters.call(ToPainteraData.kt:112)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1743)
        at picocli.CommandLine.access$900(CommandLine.java:145)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2101)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2068)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1935)
        at picocli.CommandLine.execute(CommandLine.java:1864)
        at org.janelia.saalfeldlab.paintera.conversion.PainteraConvert$Companion.main(PainteraConvert.kt:35)
        at org.janelia.saalfeldlab.paintera.conversion.PainteraConvert.main(PainteraConvert.kt)
Unable to convert into Paintera dataset: A master URL must be set in your configuration
```

**Comment by hanslovsky** [comment]
Now with better error message when no Spark master is specified:
```
No spark master specified. Use the `-Dspark.master=<master>' system property or the `--spark-master' option.
```

**Comment by hanslovsky** [comment]
I tested on CREMI sample A with the example command in the description:

```
paintera-convert to-paintera \
  --scale 2,2,1 2,2,1 2,2,1 2 2 \
  --revert-array-attributes \
  --output-container=paintera-converted.n5 \
  --container=sample_A_20160501.hdf \
    -d volumes/raw \
      --target-dataset=volumes/raw2 \
      --dataset-scale 3,3,1 3,3,1 2 2 \
      --dataset-resolution 4,4,40.0 \
    -d volumes/labels/neuron_ids

paintera-convert ts -i paintera-converted.n5 -I volumes/labels/neuron_ids -o paintera-converted.n5 -O volumes/label/neuron_ids_extracted
```
Afterwards, I run the following kscript/[imkscript](https://github.com/hanslovsky/imklib/blob/25f7f6b676df79af59b1532723be319d032cc1f0/imkscript) to confirm that everything worked as expected:
```kotlin
#!/usr/bin/env imkscript

//KOTLIN_OPTS -J-Xmx40g

import java.util.concurrent.atomic.AtomicInteger
import java.util.concurrent.Callable
import java.util.concurrent.Executors

import net.imglib2.Point
import net.imglib2.algorithm.util.Grids
import net.imglib2.loops.LoopBuilder
import net.imglib2.type.label.LabelMultisetType

val originalN5  = N5HDF5Reader("sample_A_20160501.hdf")
val convertedN5 = N5FSReader("paintera-converted.n5")
val extractedN5 = convertedN5

val originalDataset  = "volumes/labels/neuron_ids"
val convertedDataset = "$originalDataset/data/s0"
val extractedDataset = "volumes/label/neuron_ids_extracted"

val original  = N5Utils.open<UnsignedLongType>(originalN5, originalDataset)
val converted = N5Utils.open<LabelMultisetType>(convertedN5, convertedDataset)
val extracted = N5Utils.open<UnsignedLongType>(extractedN5, extractedDataset)

@Synchronized fun synchronizedPrintln(message: String?) = println(message)
val blockSize = intArrayOf(64, 64, 64)
val min = original.minAsLongs()
val max = original.maxAsLongs()

val blocks = Grids.collectAllContainedIntervals(min, max, blockSize)

val es = Executors.newFixedThreadPool(40)

val count = AtomicInteger()

val futures = blocks.map { block ->

    val oc = original[block].flatIterable().cursor()
    val cc = converted[block].flatIterable().cursor()
    val ec = extracted[block].flatIterable().cursor()
    
    es.submit(Callable<List<Point>> {
        val pointList = mutableListOf<Point>()
        while (oc.hasNext()) {
            val o = oc.next()
            val c = cc.next()
            val e = ec.next()
            if (o.integerLong != c.integerLong || !o.valueEquals(e)) pointList += Point(oc)
            // cc.next().integerLong.let { if (o.integerLong != it) synchronizedPrintln("converted error: $o $it") }
            // ec.next().let { if (!o.valueEquals(it)) synchronizedPrintln("extracted error: $o $it")}
            // synchronizedPrintln("${oc.next()} ${cc.next()} ${ec.next()}")
        }
        synchronized(count) {
            println("Finished ${count.incrementAndGet()}/${blocks.size} blocks.")
        }
        pointList
    })
}

es.shutdown()

val points = futures.flatMap { it.get() }
println("Found ${points.size} inconsistent locations:")
points.forEach { println(it) }
```
with relevant lines of output:
```
...
Finished 799/800 blocks.
Finished 800/800 blocks.
Found 0 inconsistent locations:
```

I did not find any inconsistencies when comparing to the original data (at the highest resolution level) after converting, and extracting again. I will go ahead and merge this PR. The commands and script could be converted into a test.

**Pull request merged**
