### PR TITLE
Add cluster startup scripts

### PR DESCRIPTION
**Pull request by igorpisarev**
* added flintstone & spark-janelia submodules
* startup scripts for Janelia cluster and for local use (may be handy for snapshot builds)
* build scripts for cluster and local environments that simplify setting the right maven profile

### CODE REVIEW

**Comment by hanslovsky** [comment]
What is the benefit of the local build/run scripts over just using jgo/paintera-converison-helper from pip/conda?

**Comment by igorpisarev** [comment]
Local scripts just simplify the commands a little bit for building a fat jar with spark and running it using a local spark master. (I basically copied the structure of the scripts from n5-spark, where we have both cluster and local scripts). Do you prefer the jgo way instead of fat jar for running local snapshot builds?

**Comment by hanslovsky** [comment]
I always use the jgo-based `paintera-convert` command to execute locally. Did that not work for you in some scenario?

**Comment by igorpisarev** [comment]
That works for releases, and I thought that the local scripts are useful for building and running snapshot versions e.g. for testing. But you're right, jgo should work for that too, it's just a little more involved and requires a bit more typing because you would need to specify the snapshot version, entry point, local spark-master etc.
If you don't want to mix the two, I can remove the local scripts and just keep the cluster ones.

**Comment by igorpisarev** [comment]
I've removed the local scripts in favor of jgo. I find startup scrtips for the cluster very useful and am going to go ahead and merge this PR.

**Pull request merged**
